### ISSUE TITLE
Customize the implicit cast from Error to OutgoingResponse

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#23]
Maybe make `ofError` a `dynamic function` such that users can override it?

like so:

```haxe
class Test {
    static function main() {

        I.fromString = function(s) return 2; // override the implict cast
        var i:I = 's';
        trace(i);
    }
}

abstract I(Int) from Int {
    @:from public static dynamic function fromString(v:String):I {
        return 1;
    }
}
```

**Comment by back2dos** [comment]
Truth be told, I'm inclined to get rid of that implicit cast, because pushing errors to the client is just not a good default. It seemed convenient at the time, but I'm beginning to regret it. Instead, I think users should be forced to take a minute to think about error handling (or use a framework that takes care of it).

But maybe my thinking is too radical here. OTOH, it occured to me that removing the cast will give users the possiblity to choose their own implicit casts once https://github.com/HaxeFoundation/haxe/issues/2803 is added.

So yes, I absolutely see where you're coming from, but I think the solution you are proposing creates a potential point of conflict between different libraries. I'd rather look for an alternative.

**Comment by kevinresol** [comment]
Yeah we shouldn't push raw errors to client, that's why I would like to handle that "explicity" through a customized implicit cast

**Comment by kevinresol** [comment]
I am using tink_web, my routing function (e.g. `myFunc()`) are wrapped by a `call_myFunc()` and it is where the implicit cast happens. If dynamic function is not preferred, I wonder if I have any ways to intercept the cast in a central place, without having to handle them explicitly in each routing function?

**Comment by back2dos** [comment]
Ok, it's gone. Instead there is `OutgoingResponse.reportError` to manually convert `Error` to `OutoingResponse`.

However `tink.web.Response` incorporates an error case now. With `Web.route(req, api).handleError(OutgoingResponse.reportError)` you will get the old behavior, but you can change it any way you want. Does that work for you?

**Comment by kevinresol** [comment]
@back2dos I think it will work, just looking at the API change. Closing for now. I will try it and come back if I have any problems. Thanks!
