### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_http#4]
Currently errors can be handled in `onError`, but as far as I can tell there's no way to form a response in `onError`. What I'd like to do is send a 500 response with some info if something fails. Is this something that should be handled by the application inside `serve`? I've put a try catch in there, but that only catches synchronous errors and I'm not sure how to properly handle any asynchronous error that may occur, which I think is target specific and exactly what you're doing with onError.

**Comment by back2dos** [comment]
Sorry, I must have missed this one. 

So: `onError` is quite obviously very poorly named. It is really just calling back to the application when the underlying container fails (cannot bind port, network IO fails, ...). In any of those cases there's no way to send a http response. Mostly it's to give you the opportunity to log the error or something. I think it would make sense to provide the the response that the container failed to deliver (if any) to have a finer context.

As for error handling (and exception handling) in the application, that's out of tink_http's scope. I made it a point to move that to the app's responsibility (which is also why `OutgoingResponse`'s body is an `IdealSource` so that the app has to have a strategy (e.g. end the stream if it fails (per `idealize`) or instead buffer all and return that or the error).

Async error handling is a beast. I'm very interested in any means to tame it, but in a separate lib then.
My personal strategy to deal with it is this: use tests to be reasonably sure that there are no unhandled exceptions (the day we get null safety in Haxe this should become *a lot* easier) and use Outcome/Surprise to express errors.

In general, it's insanely hard to reliably catch exceptions produced in a particular application handler, particularly if you want to map them to the affected requests (there can be multiple ones, for example if they all hit the same invalid cache and the op that recalculates it fails). This becomes all the harder if you need to catch the exceptions produced by some 3rd party lib that may be raised on a different thread or some deferred execution.

Sorry, I guess that's not the answer you were hoping for, but it's the best I have right now ;)

**Comment by benmerckx** [comment]
It's more or less the answer I was expecting. I was mostly hoping for a hint as to how I would handle asynchronous exceptions, as it was new to me. Before I started working with tink_http I didn't have much experience with async on the server side.  I'm currently experimenting with an async/await (macro) implementation in which I return every result in a Surpise. Any throw or unexpected exception is a Failure, and any Failure can be 'catched' the usual way. It seems to work very well for a first project (sending mails asynchronously via smtp through your Sink/Source) where I use my asys library.

Other than my own code I was looking for a way to reliably return 500 responses if anything (other than network errors) goes wrong in anyone's code. Accessing a property on a null value for example would land me in onError, which is why I was hoping for a way to return a response there. I'll look into other options for achieving this later. I think I still have a lot to learn before I can come to the same conslusions as you, until then I'd probably fail :)

Thanks for your explanation!
