### ISSUE TITLE
[Discussion] React native support

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_http#53]
On react native one can't pass binary data through the js<=>native bridge but only strings (or serializable objects). As a result, any binary data must live in the file system and referenced by a uri when sent by http. For example, to upload an image one does something like: `fetch(url, {method:"post", body:{uri: local_uri_of_img}})`

As a result, this doesn't match the paradigm of tink_http's client because it's body expects a source (which is binary by its nature).

So, should we support this?

If we do, I think we can change body to an enum `{Binary(s:Source); Text(s:String); FormData(f:js.html.FormData;}` (we need to provide a cross-platform FormData implementation here) and let the client handles them. On the other hand, for the same reason, the response body also need to be changed.

And I would like to know if there are any other exotic cases like this one on other framework/platform/etc...

**Comment by back2dos** [comment]
> As a result, this doesn't match the paradigm of tink_http's client because it's body expects a source (which is binary by its nature).

In computers everything is "binary by its nature" if you dig deep enough. 

Let me recapitulate why for `IncomingRequestBody` we discern two cases:

Some platforms - misguided  by genuinely good intentions - don't let you dig down to the raw binary stream. For example in PHP it already gets abstracted away for multipart requests that wind up filling `$_FILES` and `$_POST` while `php://input` is empty. We could recombine the parts into a source again for consistency, only to later parse it again which is very wasteful (even the more so because PHP is not exactly known for speed either). 

The abstraction exists not for convenience, but to acknowledge the status quo and add only as much as is needed for it to be cross platform. That's bad enough as it is, because if you're only ever deploying on node you still have to handle the `Parsed` case. On the other hand if you do have a Container implemented on top of express with body parsing, then this should come in handy to bridge the gap. 

We can thus represent opinionated choices about body parsing imposed by the environment relatively well.

That said, I'm not exactly thrilled that we had to do it. I have quite a couple of proxies written against tink_http, where I always just want to forward the body. The case that only exists to represent PHP's unfortunate design decisions makes this a bit of a nightmare. I'd rather not make it any worse.

The library's purpose is to have a small abstraction, that exposes the different environments directly (permanent vs single use server, raw vs pre-parsed bodies). Anything else can be built on top. Technically Multipart doesn't even really belong in here. It is a part of MIME (which originally is for email) and was only later reused for HTTP, but more importantly it's already an abstraction layer above. I just needed to move things forward at the time. But if you think it would help clarifying the scope of this library, we can gladly move it out.

> For example, to upload an image one does something like: `fetch(url, {method:"post", body:{uri: local_uri_of_img}})`

If react native puts us in a similar position (by imposing higher abstraction layers), then we should weigh the costs and benefits of incorporating that in our client interface. Could you please point me to the relevant docs?

> an change body to an enum {Binary(s:Source); Text(s:String); FormData(f:js.html.FormData;}

I'd rather not. Firstly, there's an implicit conversion from `String` to `Source` anyway so I don't think anything is gained by treating it separately. Secondly, `FormData` is rather clunky so implementing it across platforms is not so much fun. In the end we might even wind up having to use polyfills for it to be consistent across browsers. At the same time tink_querystring is actually built to cover that use case, unfortunately ... well ... [see for yourself](https://github.com/haxetink/tink_querystring#builder-details) ...

I guess at the bottom line for me the question is: is it possible in react native to post raw data? If so, I see no reason to add more noise. People can just use the react APIs to leverage react specific features. People can also author a tink_http based implementation of the same APIs and then write all code against that particular abstraction. Maybe when I get a chance to study it I will decide that's what I want to do myself. Still, it's a different concern, it's a different level of abstraction. If it can exist separately, it should.

**Comment by kevinresol** [comment]
> Could you please point me to the relevant docs?

It is strange enough that proper docs for this matter seems non-existent. But somehow I managed to find something in the [source code](https://github.com/facebook/react-native/blob/94666f1/Libraries/Network/FormData.js#L34-L46). This is for XHR, but with `fetch()` it is just similar. Anyway, it is quite well-known to react-native devs that uri should be used to reference a file to be uploaded. You can search that all over the web, just seems not on the official website.

> FormData is rather clunky so implementing it across platforms is not so much fun.

What I meant is a tink_http-style FormData, not necessarily complies to the js FormData spec. But I admit that I don't know much about FormData. So for now I assume you are right.

> is it possible in react native to post raw data? 

I think it is possible to do so with base64 encoding through the js-native bridge. But the bridge is slow and it is redundant to read the file into JS and then pass it back to native. (because both filesystem and networking are native). So the official recommended way is to reference the file with a string uri.

> People can just use the react APIs to leverage react specific features.

I am actually developing for both web and react-native. I have an abstraction method that uses tink_http client for web and `fetch()` on react-native. If tink_http's client has worked on react-native, such extra abstraction can be eliminated. But I understand that it is just about where to put such abstraction, given the difference exists, either built into tink_http or just let users do it. 

Maybe it is still too early to decide anything yet, because I am still finding good way to unify my code in both places. I will come back on this when I have more concrete experiences.

**Comment by back2dos** [comment]
Ok, just so I understand: the data is already on the file system and you want to POST it but avoid having to push it through the bridge?

There seems to be a react implementation for node's tcp API, so theoretically you can have streaming HTTP. Now if only there were a streaming way to get at the file. In that case the bridge shouldn't really be a noticeable bottleneck, since bandwidth will almost certainly be limited by the network.

It's so sad to see that outside node you just can't get decent streaming IO in JavaScript :D

**Comment by kevinresol** [comment]
> Ok, just so I understand: the data is already on the file system and you want to POST it but avoid having to push it through the bridge?

True.

**Comment by kevinresol** [comment]
Let's forget this for now. On RN `fetch()` and `XMLHttpRequest` are supported just like in browser. i.e. no streaming but only one big chunk of data. Unless we dive into writing the code in the native side we don't have any else options here.

**Comment by benmerckx** [comment]
@kevinresol Wouldn't this work for you? https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams#Consuming_a_fetch_as_a_stream
As I remember XMLHttpRequest had a way of reading chunks too...
